/*
 * Created by Ramesses on 2016/10/9.
 */
// Generated by CoffeeScript 1.6.3
(function() {
  requirejs.config({
    baseUrl: 'js/',
    include: ['lib/require.js'],
    paths: {
      "jquery": 'lib/jquery-1.9.1.min',
      "d3": 'lib/d3.v3.min',
      "pubsub": "lib/pubsub",
    },
    shim: {
      "d3": {
        exports: 'd3'
      }
    },
  });

  require(
    [
      (typeof window !== "undefined" && window !== null ? window.mainScript : void 0) || "application"
    ]

    );

}
).call(this);
